name: test site for me
favicon: null
layout_spectrum: 0.2903088922612369
typography_spectrum: 0.33599826670251787
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#de5976'
    - '#180406'
    - '#d5d4d0'
    - '#4d5760'
    - '#d59b7a'
  brandStrength: 0.3125
  lightness: 0.4375
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
